### ISSUE TITLE
[FTP Listing for the source code] Please consider adding (re-adding) time-based sorting functionality

### ISSUE THREAD

**Issue by rubyFeedback** [mate-desktop-legacy-archive/mate-wiki-old#1]
Hello mate devs,

I tried to find a more general entry-point for my request, but I could not find one other than this one here.

If there is a better one, please feel free to move as fits.

Situation:

If you look at the FTP listing such as here:

https://pub.mate-desktop.org/releases/1.22/

You see the available archives, and you also get the date when they were pushed/published there.

What is missing is a link that can be clicked, to sort the URLs.

     http://ftp.gnu.org/gnu/texinfo/?C=M;O=D

Or for mate-desktop:

    https://pub.mate-desktop.org/releases/1.22/?C=M;O=D

I am almost 100% sure that this was possible int he past. I remember having
been able to do so for mate-desktop.

Some months ago, possibly due to a change, this was no longer possible,
and it takes me a little bit longer to check which entries are new. I could
use a ruby script to do sorting on my own, granted - but I also like to
browser stuff manually via the browser every once in a while, without
having to use the commandline.

This brings me to my request:

- Would it be possible to re-enable the time-stamp based sorting that
was possible in the past?

I assume it requires someone who can control the FTP listing on the
webhost, so this may be unnoticed for a long time - but perhaps
someone knows whoever is handling this and it could be enabled?

I think apache httpd has some configure option that allows for
this (been some time since I used apache last).

**Comment by raveit65** [comment]
First this isn't  a ftp server, we use 443 (https) as port.
We loose time-stamps with switching to nginx server, sorry.
