### ISSUE TITLE
Feautre request: make preview like https://preview.mate-desktop.dev does

### ISSUE THREAD

**Issue by sc0w** [mate-desktop-legacy-archive/mate-wiki-old#2]
@mate-desktop/core-team  @yetist do you think is possible to do the same as https://preview.mate-desktop.dev does?

I mean something like `wiki-preview.mate-desktop.dev` or similar to improve the workflow

**Comment by yetist** [comment]
There is only one way, use the github page as the wiki preview site, and use another space as the official wiki site.

**Comment by yetist** [comment]
The official wiki site can also use the github page, but we need to create another repo that only show the site, and does not accept code commit.

**Comment by yetist** [comment]
And the mdwiki program needs to be modified to add watermark function.

**Comment by raveit65** [comment]
I want to avoid to break all links at website again with a new name/repo for official wiki.
So, 
1. i can clone existing wiki page to mate-wiki-p, where we can commit.
2. and make existing page read-only and a private repo.

Does that work?

**Comment by raveit65** [comment]
I have created/mirrored mate-wiki to mate-wiki-pre https://github.com/mate-desktop/mate-wiki-pre
And core team have admin rights for the moment. So you should able to update settings for your own.
What happens next?
When we commit at `mate-wiki-pre`repo, how we see the new commit at `mate-wiki` repo?
I can setup `mate-wiki-pre` repo as remote upstream to `mate-wiki` repo, but than we need to sync both repos by hand, like this.
```
cd mate-wiki
git remote add upstream git@github.com:mate-desktop/mate-wiki-pre.git  (one time)
git pull upstream [branch-name]   (pull from mate-wiki-pre, branch-name have to be equal!)
git push origin (push to mate-wiki)
```
Or is this to complicated?

**Comment by yetist** [comment]
@raveit65 

Thanks for create new repo for preview, let me finish this.

**Comment by yetist** [comment]
Done, please see #4.

**Comment by raveit65** [comment]
Closing as it is done. All needed information can be found at https://github.com/mate-desktop/mate-wiki/pull/4.
@yetist 
Thanks a lot.

**Comment by sc0w** [comment]
https://wiki.mate-desktop.dev is working

Thanks @yetist !
